name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    name: Format, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install mobile dependencies
        run: npm ci --prefix apps/mobile

      - name: Install api dependencies
        run: npm ci --prefix apps/api

      - name: Check formatting
        run: npm run format

      - name: Lint
        run: npm run lint # Checks code for common mistakes and bad patterns, reports things like, unsued variables, possibles bugs, react hook mistakes, stule rule problems.

      - name: Test
        run: npm test # Runs tests for all apps, files that have .test.ts or .spec.ts in the name will be run
